name: 20 SSH shells

on:
  workflow_dispatch:
    inputs:
      enable_debug:
        description: "Open SSH (tmate) in each job"
        required: true
        type: boolean
        default: true

jobs:
  shell:
    if: ${{ github.event.inputs.enable_debug == 'true' || github.event.inputs.enable_debug == true }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        idx: [1,2,3,4,5,6,7,8,9,10,
              11,12,13,14,15,16,17,18,19,20]
      max-parallel: 20

    steps:
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true   # only the triggerer can connect
          sudo: false                   # set to true only if needed
