name: 20 SSH shells
on:
  workflow_dispatch:

jobs:
  shell:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        idx: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
      max-parallel: 20
    steps:
      - uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false   # <— no GitHub profile key required
          sudo: true
